services:
  - type: web
    name: Ehub
    env: python
    region: oregon         # 利用可能なリージョン（例: oregon）
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free             # 無料プランの場合
