services:
  - type: web
    name: Ehub
    env: python
    region: oregon         # 利用可能なリージョンの中から選択
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:$PORT
    plan: free
