"""Add idea_id, comment_id, notification_type to Notification model

Revision ID: 09daf6c3005d
Revises: 2682d04ca6e8
Create Date: 2025-02-23 09:11:42.194531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09daf6c3005d'
down_revision = '2682d04ca6e8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idea_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key('fk_notification_idea', 'idea', ['idea_id'], ['id'])
        batch_op.create_foreign_key('fk_notification_comment', 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('comment_id')
        batch_op.drop_column('idea_id')

    # ### end Alembic commands ###
