"""Add actor_id to Notification

Revision ID: 2682d04ca6e8
Revises: ec4fa91f2a8b
Create Date: 2025-02-18 12:22:03.019196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2682d04ca6e8'
down_revision = 'ec4fa91f2a8b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_actor_id', 'user', ['actor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('actor_id')

    # ### end Alembic commands ###
