"""Add UserIdeaUnread model

Revision ID: d53af6ea2ad0
Revises: 376a7988b5ce
Create Date: 2025-01-25 09:49:03.895203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53af6ea2ad0'
down_revision = '376a7988b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_idea_read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_idea_read',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('idea_id', sa.INTEGER(), nullable=False),
    sa.Column('last_read_message_id', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'idea_id')
    )
    # ### end Alembic commands ###
